### ISSUE TITLE
Webview to unity

### ISSUE THREAD

**Issue by ZoedAb** [TLabAltoh/TLabWebViewVR#13]
is it possible to addlistener to a button on the webview to execute a function in unity

**Comment by TLabAltoh** [comment]
Thanks for your comment.

Callbacks to functions on the unity side from the browser are currently not possible.

This system works by connecting unity and the browser with a java plugin, but this plugin does not yet have the ability to execute unity functions.

I will add it in an update in the near future.

**Comment by TLabAltoh** [comment]
Add sendMessage(String go, String method, String message) to the plugin.

It is made to work by executing
```.js
function() {
    com.tlab.libwebview.sendMessage(String go, String method, String message)
}
```
from javascript code.

See this [document](https://docs.unity3d.com/540/Documentation/Manual/PluginsForAndroid.html#:~:text=script%20code%20using-,UnitySendMessage,-.) for the arguments.

**Comment by TLabAltoh** [comment]
``` com.libwebview.sendMessage() ``` was not working, so we fixed the plugin. The code for sending messages from js to Unity has been changed as follows.

```.js
Function() {
    window.TLabWebViewActivity.unitySendMessage(String go, String method, String message)
}
```
