### ISSUE TITLE
VideoCall

### ISSUE THREAD

**Issue by sarellano20** [TLabAltoh/TLabWebViewVR#14]
Good afternoon, how do I activate the camera and microphone permissions within a webview to view a video call?

**Comment by TLabAltoh** [comment]
Hello sarellano20, Try to see if the [UnityEngine.Android.Permission](https://docs.unity3d.com/ja/current/ScriptReference/Android.Permission.html) structure works for granting permissions. I have not verified this myself, so please let me know if it does not work.

**Comment by sarellano20** [comment]
The pop-up to activate the camera and microphone still does not work, even after activating permissions :(

**Comment by TLabAltoh** [comment]
TLabWebView has not yet implemented the ability to capture pop-ups such as Toast. It is possible that popups are just not displayed and are actually functioning in a way that is not visible.

We plan to add popup capture to the plugin in the future.

**Comment by TLabAltoh** [comment]
If possible, could you provide a screenshot of the screen where the problem is occurring?

**Comment by TLabAltoh** [comment]
It was found that WebView was rejecting microphone permissions. A corrected version is now available in the repository.

**Comment by sarellano20** [comment]
Man u really amazing!
