### ISSUE TITLE
Is there any api for resizing webview?

### ISSUE THREAD

**Issue by rinekso** [TLabAltoh/TLabWebViewVR#17]
This is amazing plugin and I try to make new UX for web browser vr. It will be really great if there is function for resizing it. But I can't find it. I don't know what I missed it.

**Comment by TLabAltoh** [comment]
Webview resizing is an unimplemented feature, but I would like to implement it in a future update.

**Comment by TLabAltoh** [comment]
Resize API added in latest commit

https://app.gitbook.com/o/BEOtLe2RJogUYj62ljWp/s/mRKt4CGSxyWYs97naGI6/documentation-en/scripting-api#resize
