### ISSUE TITLE
Missing "Scenes" Folder in Assets/TLab/TLabWebViewVR/OculusIntegration/

### ISSUE THREAD

**Issue by HafizMSaad** [TLabAltoh/TLabWebViewVR#18]
Upon navigating to the directory _Assets/TLab/TLabWebViewVR/OculusIntegration/_, I observed that the "**Scenes**" folder is missing. This prevents me from accessing the required scene file. Could you please investigate and resolve this issue? Thank you.

**Comment by HafizMSaad** [comment]
> Upon navigating to the directory _Assets/TLab/TLabWebViewVR/OculusIntegration/_, I observed that the "**Scenes**" folder is missing. This prevents me from accessing the required scene file. Could you please investigate and resolve this issue? Thank you.

Instead, I discovered the **TLabWebViewVR.prefab** located within _Assets/TLab/TLabWebViewVR/OculusIntegration/_

**Comment by TLabAltoh** [comment]
Could it be that you are referring to [this repository](https://github.com/TLabAltoh/TLabWebViewVR-OculusIntegration-2022)? [Here](https://github.com/TLabAltoh/TLabWebViewVR-OculusIntegration-2022/tree/master/Assets%2FScenes) is a sample scene.

By the way, thank you for pointing out the typo in README.md. I had not noticed it for a long time.

**Comment by HafizMSaad** [comment]
Exactly, I am referring to the mentioned repository. The sample scene does not align with the discussion points outlined in the readme, as it lacks parameters such as URL, DlOption etc.

**Comment by HafizMSaad** [comment]
My bad, I overlooked the _TLabWebViewVR/TLabWebView/WebView_ prefab attached to Sample Scene, where the WebView contains parameters for URL and DlOption.
