### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by heisenbergg-0** [TLabAltoh/TLabWebViewVR#2]
Hey man this is an amazing asset, at some point will there be a way to be compatible with the Mixed Reality input, or some way to make it work with it?
Thank you so much!

**Comment by TLabAltoh** [comment]
Thanks for your comment !

I will release MRTK support for TLabWebView as a new repository in the near future.

Please note that I don't have HoloLens, so I can only support MRTK for Oculus Quest 2 :⁠^⁠)

**Comment by TLabAltoh** [comment]
# Mixed Reality Toolkit Supported
TLabWebView operation using Mixed Reality input is now supported

## Demonstration video
https://youtu.be/_oWE5RlsHLk

<img src="https://github.com/TLabAltoh/TLabWebViewVR/assets/121733943/e7e76886-9aec-48ce-94ae-87f8b8fecb22" width="512"></img>

## Sample project
https://github.com/TLabAltoh/TLabWebViewMRTK

This sample works only with Oculus Quest, but I hope it will be helpful.

**Comment by heisenbergg-0** [comment]
you're amazin man, thnks!!
