### ISSUE TITLE
Inquiring about Methods to Detect WebView Completion(NOT AN ISSUE)

### ISSUE THREAD

**Issue by HafizMSaad** [TLabAltoh/TLabWebViewVR#20]
I'm currently working on a project where I need to inject JavaScript into a WebView instance within my application. However, I'm encountering difficulty determining when the WebView has finished loading its content, which is crucial for the injection process to be executed accurately.

**Comment by TLabAltoh** [comment]
please try ``` onPageFinish ```. it is a string type variable that can define javascript to be called when page load was finished.

the property outlined in blue is that.

![315887836-610f3d14-82c0-434d-a1ee-8b0346be1664 (1).png](https://github.com/TLabAltoh/TLabWebViewVR/assets/121733943/7af9c0c3-1102-4a3a-8aed-b78985f3f7ab)

**Comment by HafizMSaad** [comment]
> please try `onPageFinish`. it is a string type variable that can define javascript to be called when page load was finished.
> 
> the property outlined in blue is that.
> 
> ![315887836-610f3d14-82c0-434d-a1ee-8b0346be1664 (1).png](https://private-user-images.githubusercontent.com/121733943/315898939-7af9c0c3-1102-4a3a-8aed-b78985f3f7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzE4NjAsIm5iZiI6MTcxMTEzMTU2MCwicGF0aCI6Ii8xMjE3MzM5NDMvMzE1ODk4OTM5LTdhZjljMGMzLTExMDItNGEzYS04YWVkLWI3ODk4NWYzZjdhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxODE5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDdiN2JkY2I4NTM5YWQ0MzJlMTJhMGU1NzViNTZmZDVlMWRjNWQwYWRkOGI0ODdkMzc5NzA4ZDkwNjQxM2EzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dcGhc887zK8W2UBJtzYQaoPZuk6J31R1qFznJeY_4i0)

I'm uncertain about its usage; despite my attempts, I didn't succeed. I expected a callback or delegate method to notify when the webview finishes loading.

**Comment by TLabAltoh** [comment]
The attached image is from a different issue. Please ignore the green border.

here is a javascript sample that works with ``` onPageFinish ``` as well when copy as a string variable.

[original soirce](https://github.com/TLabAltoh/TLabWebViewVR-OculusIntegration-2022/blob/master/Assets%2FTLab%2FTLabWebViewVR%2FOculusIntegration%2FScripts%2FSearchBarInteractionSample.cs)

```javascript
var elements = [];

function searchShadowRoot(node, id) {
    if (node == null) {
        return;
    }

    if (node.shadowRoot != undefined && node.shadowRoot != null) {
        if (!elements.includes(node.shadowRoot)) {
            elements.push(node.shadowRoot);
        }
        searchShadowRoot(node.shadowRoot, id);
    }

    for (var i = 0; i < node.childNodes.length; i++) {
        searchShadowRoot(node.childNodes[i], id);
    }
}

elements.push(document);
searchShadowRoot(document, 'input');
searchShadowRoot(document, 'textarea');

function focusin (e) {
    const target = e.target;
    if (target.tagName == 'INPUT' || target.tagName == 'TEXTAREA') {
        window.TLabWebViewActivity.unitySendMessage('SearchBar', 'OnMessage', 'Foucusin');
    }
}

function focusout (e) {
    const target = e.target;
    if (target.tagName == 'INPUT' || target.tagName == 'TEXTAREA') {
        window.TLabWebViewActivity.unitySendMessage('SearchBar', 'OnMessage', 'Foucusout');
    }
}

for (var i = 0; i < elements.length; i++) {
    elements[i].removeEventListener('focusin', focusin);
    elements[i].removeEventListener('focusout', focusout);

    elements[i].addEventListener('focusin', focusin);
    elements[i].addEventListener('focusout', focusout);
}
```

**Comment by HafizMSaad** [comment]
Can I specify a piece of code as a value for the onPageFinish string, so that once the WebView has finished loading its content from the URL, the specified code will execute? This piece of code could potentially inject JavaScript into the WebView.

**Comment by TLabAltoh** [comment]
Yes, Javascript is executed when page loading is finished.

**Comment by HafizMSaad** [comment]
In my `TLabWebViewSample` class, I have a method called `handleJavaScriptInjection`. This method is normally invoked with a **3-second delay** to ensure the webview has finished loading before injecting JavaScript successfully. While this approach works fine most of the time, there are occasional failures. I considered increasing the delay time to mitigate this issue. However, when I attempted to call this method directly from the `onPageFinish` event handler, the JavaScript injection didn't occur as expected. It seems the method wasn't invoked.

**Comment by TLabAltoh** [comment]
Please check the following.

1. Javascript does not contain comment out string (like //. only /**/ allowed). 

2. onPageFinish was registered by inspector. or SetOnPageFinish(). onPageFinish string value can access and change directly by c# script, but that is not refrected to webview.

3. onPageFinish contain Javascript code only.

I do not think this is an execution timing issue.

**Comment by HafizMSaad** [comment]
```
using UnityEngine;
using UnityEngine.SceneManagement;
using Newtonsoft.Json;

namespace TLab.Android.WebView
{
	public class TLabWebViewSample : MonoBehaviour
	{
		[SerializeField] private TLabWebView m_webView;
		[SerializeField] private SearchBar m_seachBar;

		public void StartWebView()
		{
			m_webView.StartWebView();
		}

		void Start()
		{
			StartWebView();
            LoggerUtility.LogMethodName(additionalInfo: "TLabWebViewSample: Start");
            scheduleJavaScriptInjectionHandling();
			m_seachBar.gameObject.SetActive(false);
		}

		void Update()
		{
#if UNITY_ANDROID
			m_webView.UpdateFrame();
#endif
		}

        #region JavaScript Injection

        public void scheduleJavaScriptInjectionHandling()
        {
            Invoke("handleJavaScriptInjection", 5); // Invoke the method after a delay of 3 seconds
        }

        public void handleJavaScriptInjection()
        {
            if (!FileUtility.CheckFileContentsNotEmpty(ElevateConfig.Instance.fileContent))
            {
                LoggerUtility.LogMethodName(additionalInfo: "file contents are empty");
            }
            else
            {
                LoggerUtility.LogMethodName(additionalInfo: "file contents are not empty");
                foreach (string line in ElevateConfig.Instance.fileContent)
                {
                   LoggerUtility.LogMethodName(additionalInfo: line);
                }
                InjectJavaScriptTo(type: "", fileContent: ElevateConfig.Instance.fileContent);
            }
        }

        public void InjectJavaScriptTo(string type, string[] fileContent)
        {
            LoggerUtility.LogMethodName();
            string buttonId = GetHiddenButtonWebView(type); // Get the button ID based on the type
            if (string.IsNullOrEmpty(buttonId))
            {
                LoggerUtility.LogMethodName(additionalInfo: "Button ID is not defined for the given type: " + type);
                return;
            }

            // Convert the array of strings into a single JSON array string
            string arrayString = JsonConvert.SerializeObject(fileContent);

            // Construct the JavaScript code to set the value of the hidden button and trigger its click event
            string javaScriptString =
                $"var button = document.getElementById('{buttonId}');" +
                $"button.value = JSON.stringify({{ fileContent: {arrayString} }});" +
                "button.click();";

            // Load the JavaScript code into the WebView
            m_webView.EvaluateJS(javaScriptString);
        }

        private string GetHiddenButtonWebView(string type)
        {
            return "file-content-button";
        }

        #endregion JavaScript Injection

    }
}

```

Here is the code snippet for my `TLabWebViewSample` class. I intend to invoke the `handleJavaScriptInjection` method to inject JavaScript into the webview once it has finished loading its initial URL content.

**Comment by TLabAltoh** [comment]
Please try to use [this](https://tlabgames.gitbook.io/tlabwebview/documentation-en/scripting-api#:~:text=send%20a%20message%20from%20javascript%20to%20unity.) on javascript. this method can call unity function that arguments are just a string.

**Comment by HafizMSaad** [comment]
> Please try to use [this](https://tlabgames.gitbook.io/tlabwebview/documentation-en/scripting-api#:~:text=send%20a%20message%20from%20javascript%20to%20unity.) on javascript. this method can call unity function that arguments are just a string.

Are you suggesting that I use `unitySendMessage` to call my `handleJavaScriptInjection` method upon `onPageFinish`?

**Comment by TLabAltoh** [comment]
Right. but unitySendMessage can call a function that takes only one argument, a string. so you need to prepare a new function that takes only a string as an argument.
