### ISSUE TITLE
Seeking Clarification on Zoom Functionality Controls in WebView(NOT AN ISSUE)

### ISSUE THREAD

**Issue by HafizMSaad** [TLabAltoh/TLabWebViewVR#21]
As I'm integrating WebView into my application, I've noticed that there are zoom in and zoom out functions available. However, I require clarification on the specific controls (in the VR headset's controllers) that facilitate this zoom functionality within the WebView.

**Comment by TLabAltoh** [comment]
There are not system that zoom in/out with pinch operation. to use the zoom in/out function, you need to create a GUI interface (such as a button) that calls WebView zoom in/out. and so you need to take care of webpage are supported zoom operation. check [this document](https://developer.mozilla.org/ja/docs/Web/CSS/zoom).
