### ISSUE TITLE
Utilize JNI AttachCurrentThread for Heavy Operations

### ISSUE THREAD

**Issue by HafizMSaad** [TLabAltoh/TLabWebViewVR#24]
**This is a heavy operation and should be infrequent. To optimize, use JNI AttachCurrentThread on calling thread**
This message is continuously logging in the debugger window, creating an infinite stream of output.

**Comment by TLabAltoh** [comment]
This problem has been fixed recently, [please see here](https://github.com/TLabAltoh/TLabWebViewVR/issues/16) to update the repository and submodule.

**Comment by TLabAltoh** [comment]
Add the following symbols to Project Settings --> Player --> Other Settings (to be used at build time)

```
UNITYWEBVIEW_ANDROID_SUPPORT_OCULUS
```

**Comment by HafizMSaad** [comment]
> Add the following symbols to Project Settings --> Player --> Other Settings (to be used at build time)
> 
> ```
> UNITYWEBVIEW_ANDROID_SUPPORT_OCULUS
> ```

Do you suggest to add `UNITYWEBVIEW_ANDROID_SUPPORT_OCULUS`  under **Scripting Define Symbols**?

**Comment by TLabAltoh** [comment]
Yes, please add ```UNITYWEBVIEW_ANDROID_SUPPORT_OCULUS``` to **Scriptiong Define Symbols.**
