### ISSUE TITLE
 Content Overlapping Issue on New Custom-Tailored Headset

### ISSUE THREAD

**Issue by HafizMSaad** [TLabAltoh/TLabWebViewVR#28]
I am encountering an issue with my new custom-tailored headset where the content is overlapping. When I try to use the headset, the content appears to be overlapping, making it difficult to view or interact with. This issue occurs consistently and affects the usability of the device. I have tried restarting the device, but the problem persists. Any assistance in resolving this issue would be greatly appreciated. Thank you!
@TLabAltoh

**Comment by TLabAltoh** [comment]
Sorry for forgetting to answer this. 

Could you send me screenshot or sketch about the situation of content view overwrapping? If you do not want to publish screenshot here, you can send me the picture by email.

**Comment by TLabAltoh** [comment]
Sure, here is my email∶tlabaltoh@gmail.com

**Comment by HafizMSaad** [comment]
@TLabAltoh can it be fixed by adjusting the zoom?

**Comment by TLabAltoh** [comment]
I have connected email to Zoom account, now you can add Zoom account through this email.

**Comment by TLabAltoh** [comment]
Maybe I do not understand the problem correctly, low resolution of the web (not texture) have possible to cause content overlapping and it is difficult to interact. are there any improvements when modifly webview's resolusion propaty.

**Comment by HafizMSaad** [comment]
the issue had been fixed increasing the size of the web-view @TLabAltoh :)
