### ISSUE TITLE
"is it possible to get values from web" can you add it for vr also

### ISSUE THREAD

**Issue by SAKTHIVISHNU25** [TLabAltoh/TLabWebViewVR#3]

**Comment by SAKTHIVISHNU25** [comment]
I'm facing a tight deadline with this. If you have any availability in your schedule, I would greatly appreciate your help.

**Comment by TLabAltoh** [comment]
OK, I'll update soon.

**Comment by TLabAltoh** [comment]
I am now checking the operation.

**Comment by TLabAltoh** [comment]
# This repository now also allows HTML capture.
Sorry for the delay.
Please let me know if it does not work.

**Comment by SAKTHIVISHNU25** [comment]
It's working fine. Thanks :-)

**Comment by TLabAltoh** [comment]
Glad to hear it !

**Comment by SAKTHIVISHNU25** [comment]
how to clear cache of web

**Comment by TLabAltoh** [comment]
I will try to get the plugin to support cache deletion tomorrow.

**Comment by TLabAltoh** [comment]
# Deleting the cache is now supported.
Sorry for the delay ...
Deleting the cache is now supported.
```
Assets/TLab/TLabWebView/Script/TLabWebView.cs
```
```
public void ClearCache(bool includeDiskFiles)
```
```
public void ClearCookie()
```
```
public void ClearHistory()
```
