### ISSUE TITLE
Unable to authenticate on this browser.

### ISSUE THREAD

**Issue by ChrisTriant** [TLabAltoh/TLabWebViewVR#31]
Trying to connect into our website and I receive the error bellow:
Unable to authenticate on this browser
Your browser is not secure enough to make authentication work. Try updating your browser or use a newer browser

**Comment by ChrisTriant** [comment]
The website is still private since it is under development and can only be accessed through vpn

**Comment by TLabAltoh** [comment]
Ok. When I find the cause of the problem. I will release the fixed one and notice it here.

**Comment by ChrisTriant** [comment]
That's great. Thanks

**Comment by ChrisTriant** [comment]
The issue was solved by clearing the cache through the ClearCache function of the webview.
