### ISSUE TITLE
Asset migration guide

### ISSUE THREAD

**Issue by StefanCiobanu1989** [TLabAltoh/TLabWebViewVR#6]
Hi,
First off, thank you for making this public, i have managed to get it working using this project however i have tried migrating the webview to a different project but without success. I have seen you have some videos on youtube can you create a quick video about how to properly migrate the webview and keyboard to a different project, pretty please? Thank you!

**Comment by TLabAltoh** [comment]
👍I'll make it after the current work settles down. Just a moment, please.

**Comment by StefanCiobanu1989** [comment]
you are a god, thank you very much

**Comment by TLabAltoh** [comment]
Sorry for the delay. please refer to this video.

https://youtu.be/_Tj6pHsAz6M

**Comment by StefanCiobanu1989** [comment]
> Sorry for 6M
the delay. please refer to this video.
> 
> https://youtu.be/_Tj6pHsAz6M
Bless you soul :D

**Comment by StefanCiobanu1989** [comment]
Coffe on it's way
