### ISSUE TITLE
how to change view from mobile to desktop.

### ISSUE THREAD

**Issue by StefanCiobanu1989** [TLabAltoh/TLabWebViewVR#8]
Hi again,
The websites are always displayed in their mobile form, is there a way to change that ? It tried changing TLabWebView and WebView width and height related properties to 1920x1080 and it still shows as the mobile website. Thanks!

**Comment by TLabAltoh** [comment]
Hi Stefan,
A sample of displaying WebView in desktop form has been added to the repository.
This sample changes the user agent of WebView to change the page display to desktop.

![output](https://github.com/TLabAltoh/TLabWebViewVR/assets/121733943/f1b07df5-23cf-438c-81cb-b80af6922ee3)

```c#
// WebViewSample.cs
public void SetUserAgent(string ua)
{
    // Change user agent (Switches the browser display to the desktop form).
    // WebView.SetUserAgent(string ua)
    m_webView.SetUserAgent("Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0");
}
```

``` SetUserAgent(string ua) ``` is a new feature added in this update, so clone the latest version of the repository when checking the operation.

See also User agent settings.
[mozilla user-agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox)

**Comment by StefanCiobanu1989** [comment]
God like! Thank you!
