### ISSUE TITLE
In search of wisdom yet again

### ISSUE THREAD

**Issue by StefanCiobanu1989** [TLabAltoh/TLabWebViewVR#9]
hi again, bare with, more coffees are coming.
I'm trying to assign an url on runtime to a webview but 
i have this loop :
```
TLabWebView[] webviews = duplicate.GetComponentsInChildren<TLabWebView>();
TextMeshPro[] textMeshes = duplicate.GetComponentsInChildren<TextMeshPro>();
foreach (TLabWebView webView in webviews)
{
        webView.SetUserAgent("Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0");
        webView.LoadUrl(url);

        foreach (TextMeshPro textMesh in textMeshes)
        {     
            if(textMesh.name == "DebugText"){
                textMesh.text = "UserAgent: "+ webView.GetUserAgent() + "   Url: "+ webView.GetUrl();
            }
        }
}
```
The Webview is structured as such in my project :
![image](https://github.com/TLabAltoh/TLabWebViewVR/assets/86718588/ca61db80-774d-4e72-bff9-0ab14381eb14)
 
 The "duplicate" object from `duplicate.GetComponentsInChildren<TLabWebView>();` represents the assigned EmptyWebView object from the screenshot.

Problem i'm having is: 
```
webView.SetUserAgent("Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0");
webView.LoadUrl(url);
```
dont seem to work as ` textMesh.text = "UserAgent: "+ webView.GetUserAgent() + "   Url: "+ webView.GetUrl();` results in UserAgent and Url being empty. The "url" variable does contain a text string.

If something comes to mind please let me know. The webview is being found, the TextMeshPro object is being found but the set "SetUserAgent" and "LoadUrl" dont seem to get assigned. Thank you!

P.S. I have attempted to add a new function in the TLabWebView.cs called GetUrl() which should return the url on which the page is on, but because of this issue i cant really tell if it's working: 
```
public string GetUrl()
{
	if (!m_webViewEnable)
	{
		return null;
	}

	string currentUrl = null;

#if UNITY_ANDROID
	if (Application.isEditor) return null;

	// Assuming m_NativePlugin is your reference to the native webview component.
	currentUrl = m_NativePlugin.Call<string>("getCurrentUrl");
#endif

	return currentUrl;
}
```

**Comment by TLabAltoh** [comment]
Hello.

GetUserAgent() is a function to retrieve the result obtained by CaptureUserAgent(), so please execute it like this.


```

    public async void GetUserAgent()

    {

        m_webView.CaptureUserAgent();


        await Task.Delay(500);

        Debug.Log("User Agent: " + m_webView.GetUserAgent());

    }

```

CaptureaUserAgent() is executing asynchronously, so please wait a little before GetUserAgent().


I will also add a function to get the URL later.

**Comment by StefanCiobanu1989** [comment]
out of curiosity, how many instances can you spawn before it gets laggy ? With just one instance and 
Web Width = 1280, 
Web Height 720, 
Tex Width 1280 
Tex Height 720 
it starts feeling sluggish , and if i spawn 4 more webviews it feels like it's 10FPS when moving my head around. Sorry to bother, but i need to figure out if i'm doing something wrong..
